version: '3.8'

services:
  # 1. DATABASES SERVICE
  redis:
    image: redis:alpine
    container_name: churn_redis
    ports:
      - "6379:6379"
    restart: always

  # 2. API SERVICE
  api:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: churn_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_TIMEOUT=5.0
    restart: always

  # 3. UI SERVICE
  ui:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: churn_ui
    ports:
      - "8501:8501" 
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    restart: always